name    'jhoblitt-perlbrew'
version '0.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-perlbrew'
source 'https://github.com/jhoblitt/puppet-perlbrew.git'
summary 'perlbrew installaation'
summary 'perlbrew installaation'
dependency 'puppetlabs/stdlib', '>= 4.2.0'
dependency 'maestrodev/wget', '>= 1.2.2'
